runtime: nodejs18
env: standard

service: default
instance_class: F1

handlers:
  - url: /static
    static_dir: build/static
    secure: always

  - url: /(.*\.(json|ico|js|css|png|jpg|jpeg))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|css|png|jpg|jpeg)$
    secure: always

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always

env_variables:
  REACT_APP_API_URL: "https://api.spring-radio.com"
