runtime: nodejs18
env: standard

service: api
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  NODE_ENV: "production"
  GOOGLE_CLOUD_PROJECT_ID: "spring-radio"
  GOOGLE_CLOUD_BUCKET_NAME: "spring_radio_storage"
  # Note: In App Engine, you don't need to specify GOOGLE_CLOUD_KEY_FILE
  # as it uses the default service account credentials

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
